version: '3.9'
services:
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Substitui o comando padrão da imagem do node
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/testtwo
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
  # Serviço que irá rodar o mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      # Garanta que não haverá conflitos de porta com um mongodb que esteja
      # rodando localmente
      - "27017:27017"
